config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "application#index"

  resources :teams
  post "/add_result", to: "teams#add_result"
  resources :players
  post "/invest", to: "players#invest"
  resources :results
  resources :shares, only: [:destroy]
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :team, :class_name => 'Team'
  belongs_to :opponent, :class_name => 'Team', optional: true

  def self.points_map
    {
      "Loss" => 0,
      "Group Stage Draw" => 100,
      "Group Stage Win" => 200,
      "Bonus: Group Stage 3rd Place" => 100,
      "Bonus: Group Stage 2nd Place" => 200,
      "Bonus: Group Stage 1st Place" => 400,
      "Round of Sixteen Win" => 400,
      "Quarter-Final Win" => 900,
      "Semi-Final Win" => 1200,
      "Cup Champion" => 1500,
    }
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:destroy]
  before_action :require_admin

  def index
    @results = Result.joins(:team).order('teams.name ASC')
  end

  def destroy
    @result.destroy
    redirect_back fallback_location: results_url, notice: 'Result was successfully deleted.'
  end

  private
    def set_result
      @result = Result.find(params[:id])
    end

    def require_admin
      unless current_user&.admin?
        redirect_to(root_path)
      end
    end
end

app/helpers/result_helper.rb
module ResultHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/index.erb
<% if current_user&.admin? %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Team</th>
        <th scope="col">Result</th>
        <th scope="col">Opponent</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
      <tbody>
      <% @results.each do |result| %>
      <tr>
          <td><%= result.team.name %></td>
          <td><%= result.text %></td>
          <td><%= result.opponent&.name %></td>
          <td>
            <%= form_with model: result, method: :delete, url: result_path(result), data: { turbo: false } do |form| %>
              <%= form.submit 'X', class: 'btn btn-danger p-0 ps-2 pe-2' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>