config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "application#index"

  resources :teams
  post "/add_result", to: "teams#add_result"
  resources :players
  post "/invest", to: "players#invest"
  resources :results
  resources :shares, only: [:destroy]
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :user
  has_many :shares
  has_many :teams, through: :shares

  validates :name, presence: true, uniqueness: true

  def display_name
    @display_name ||= nickname || name
  end

  def points
    @points ||= shares.inject(0) { |total , share| total + share.points } || 0
  end

  def spend_credits(amount)
    raise StandardError, "Not enough Credits!" if credits < amount.to_i
    update(credits: credits - amount.to_i)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  skip_before_action :ensure_player_profile, only: [:new, :create]
  before_action :ensure_single_player_profile, only: [:new, :create]
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  def index
    @players = Player.all.sort_by(&:points).reverse
  end
  
  def show
    player_team_ids = @player.shares.map{|s| s.team_id }
    @unbought_teams = Team.order(name: :asc).reject{|t| player_team_ids.include?(t.id) }
    @shares = Share.where(player_id: @player.id).sort_by { |share| [-share.points, -share.amount] }
    @amounts = (5..50).step(5).select { |i| i <= @player.credits }.reverse
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    @player.user = current_user

    if @player.save
      redirect_to new_player_path
    else
      flash[:alert] = @player.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @player.update(player_params)
      redirect_to @player
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit
  end

  def destroy
  end

  def invest
    @player = Player.find(params[:player])
  
    raise StandardError, "Max 6 investments!" if @player.shares.count >= 6
    raise StandardError, "Amount must be positive number!" unless params[:amount].to_i > 0
    raise StandardError, "Amount cannot exceed 50!" if params[:amount].to_i > 50

    if found = @player.shares.find { |s| s.team.id == params[:team].to_i}
      raise StandardError, "You already have shares for #{found.team.name}!"
    end

    ActiveRecord::Base.transaction do
      @player.spend_credits(params[:amount])
      share = Share.create({:amount => params[:amount], :player_id => params[:player], :team_id => params[:team]})
      flash[:notice] = "Bought #{share.amount} shares for #{share.team.name}"
    end

    redirect_to @player
  rescue StandardError => e
    flash[:alert] = e.message
    redirect_to @player
  end

  private
    def set_player
      @player = Player.find(params[:id])
    end

    def player_params
      params.require(:player).permit(:name, :nickname)
    end

    def ensure_single_player_profile
      if current_user&.player.present?
        redirect_to current_user&.player, alert: 'You already have a player profile.'
      end
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<div class="container p-3">
  <%= form_with model: @player do |form| %>
    <div class="mb-4">
      <div>
        <%= form.label :name,"Real Name",  class: "form-label" %>
        <%= form.text_field :name, class:"form-control", maxlength: 25 %>
        <% @player.errors.full_messages_for(:name).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
      <br>
      <div>
        <%= form.label :nickname, "Display Name", class: "form-label" %>
        <%= form.text_field :nickname, class:"form-control", maxlength: 12 %>
        <% @player.errors.full_messages_for(:nickname).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
    </div>

    <div>
      <%= form.submit class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/players/_player_list.html.erb
<h1>Players</h1>
<ul class="list-group">
  <% @players.each do |player| %>
    <li class="list-group-item">
      <%= link_to player.display_name, player %>
    </li>
  <% end %>
</ul>

app/views/players/create.html.erb
<h1>Players#create</h1>
<p>Find me in app/views/players/create.html.erb</p>

app/views/players/destroy.html.erb
<h1>Players#destroy</h1>
<p>Find me in app/views/players/destroy.html.erb</p>

app/views/players/edit.html.erb
<h1>Edit Profile</h1>
<%= render "form" %>

app/views/players/index.html.erb
<div class="d-flex flex-row justify-content-between align-items-start">
  <h1>Players</h1>
</div>
<!--
<ul class="list-group">
  <% rank = 0 %>
  <% @players.each do |player| %>
    <li class="list-group-item">
      <span><%= rank = rank +1 %>. <%= link_to player.display_name, player %>: <%= player.points > 0 ? ApplicationHelper.strip_trailing_zero(player.points.round(2)) : 0 %></span>
    </li>
  <% end %>
</ul>
-->

<table class="table">
  <thead>
    <tr>
      <th scope="col" class="table-index">Rank</th>
      <th scope="col">Player</th>
      <th scope="col">Points</th>
    </tr>
  </thead>
  <tbody>
    <% rank = 0 %>
    <% @players.each do |player| %>
      <tr>
        <th class="table-index"><%= rank = rank + 1 %>.</th>
        <td><%= link_to player.display_name, player %></td>
        <td><%= player.points > 0 ? ApplicationHelper.strip_trailing_zero(player.points.round(2)) : 0 %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/players/new.html.erb
<h1>What is your name?</h1>
<%= render "form" %>

app/views/players/show.html.erb
<div class="d-flex flex-row flex-wrap justify-content-between align-items-end">
  <h1 class="m-0"><%= @player.display_name %></h1>
  <div>
    <% if current_user&.player && current_user&.player == @player %>
      <%= link_to "Edit", edit_player_path(@player), class: 'btn btn-secondary p-0 ps-2 pe-2'  %>
      <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn btn-danger p-0 ps-2 pe-2'  %>
    <% end %>
  </div>
</div>
  <% unless @player.name == @player.display_name  %>
    <h6 class="m-0">(<%= @player.name %>)</h6>
  <% end %>
  <% if current_user&.admin? %>
    <h6 class="m-0"><%= @player.user.email %></h6>
  <% end %>
<hr class="hr">

<% unless @tourny_started %>
  <h3 class="mb-3"> Credits Remaining: <%= @player.credits %></h3>
<% else %>
  <h3><%= @player.points > 0 ? ApplicationHelper.strip_trailing_zero(@player.points.round(2)) : 0 %> Points</h3>
<% end %>

<hr class="hr">
<div class="mb-3">
  <h4>Shares<%= ' (Max 6)' unless @tourny_started %></h4>
  <% unless @debug_mode || current_user&.player == @player || @tourny_started %>
    <div>Hidden until June 14th</div>
  <% else %>
    <table class="table">
      <% if @shares.count > 0 %>
        <thead>
          <tr>
            <th scope="col">Team</th>
            <th scope="col">Shares</th>
            <% if @debug_mode || @tourny_started %>
              <th scope="col">Equity</th>
              <th scope="col">Points Earned</th>
            <% end %>
            <% if @debug_mode || !@tourny_started %>
              <th scope="col">Delete</th>
            <% end %>

          </tr>
        </thead>
        <tbody>
          <% @shares.each do |share| %>
          <tr>
            <td><%= link_to share.team.name, share.team %></td>
            <td><%= share.amount %></td>
            <% if @debug_mode || @tourny_started %>
              <td><%= ApplicationHelper.strip_trailing_zero share.player_equity_percent.round(2) %>%</td>
              <td>
                  + <%= ApplicationHelper.strip_trailing_zero share.points.round(2) %>
              </td>
            <% end %>
            <% if @debug_mode || !@tourny_started %>
              <td>
                <%= form_with model: share, method: :delete, url: share_path(share), data: { confirm: 'Are you sure?' } do |form| %>
                  <%= form.submit 'X', class: 'btn btn-danger p-0 ps-2 pe-2' %>
                <% end %>
              </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      <% else %>
        <div >No Shares Invested</div>
      <% end %>
    </table>
  <% end %>
  
</div>

<% if @debug_mode || (@player == current_user&.player && !@tourny_started)%>
  <div class="container text-bg-light p-3">
    <% if @player.credits > 0 %>
      <h5>Invest</h5>
      <%= form_with url: "/invest", method: :post do |form| %>
        <%= form.hidden_field :player, value: @player.id %><br>
        <div class="mb-2">
          <div class="d-flex flex-row">
            <div class="col-8 ps-0">
              <%= form.label :team, {}, class: "form-label" %><br>
              <%= form.select :team, @unbought_teams.map{|t| [t.name, t.id]}, {}, class: "form-select" %><br>
            </div>
            <div class="col-4 ps-4">
              <%= form.label :amount, {}, class: "form-label" %><br>
              <%= form.select :amount, options_for_select(@amounts), {}, class: "form-select" %>
            </div>
          </div>
        </div>

        <div>
          <%= form.submit 'Invest!', class: "btn btn-success" %>
        </div>
      <% end %>
    <% else %>
      <h5>You're all set!</h5>
      <div>You may continue making changes until June 14th.</div>
    <% end %>
  </div>
<% end %>

app/views/players/update.html.erb
<h1>Players#update</h1>
<p>Find me in app/views/players/update.html.erb</p>