config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "application#index"

  resources :teams
  post "/add_result", to: "teams#add_result"
  resources :players
  post "/invest", to: "players#invest"
  resources :results
  resources :shares, only: [:destroy]
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-light bg-light pe-2 ps-2 d-flex flex-row justify-content-between sticky-top">
  <a class="navbar-brand p-0 m-0 ps-2" href=<%=root_path%>>
    <h6 class="m-0"><strong>EuroCup</strong>2024</h6>
    <h5 class="m-0">INVE<strong>STARS</strong></h5>
  </a>

  <% if current_user&.player %>
    <ul class="navbar-nav d-flex flex-row ">
      <li class="nav-item pe-2">
        <%= link_to 'Teams', teams_path, class: 'btn btn-dark p-1 ps-2 pe-2' %>
      </li>
      <li class="nav-item pe-2">
        <%= link_to 'Players', players_path, class: 'btn btn-dark p-1 ps-2 pe-2' %>
      </li>
      <% if current_user&.player %>        
        <li class="nav-item pe-2">
          <%= link_to 'Me', player_path(current_user.player), class: 'btn btn-success p-1 ps-2 pe-2' %>
        </li>
      <% end %>
    </ul>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EuroCup InveStars</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="container mt-2">
      <!-- Display flash notices -->
      <% if flash[:notice].present? %>
        <div class="flash-notice">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <!-- Display flash alerts -->
      <% if flash[:alert].present? %>
        <div class="flash-alert">
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
      <div class="mb-3"></div>
    </div>
  </body>
</html>